%%
%% @doc This module is auto-generated by rebar3_egrpc_plugin.
%%
%% This module was generated on 2025-06-15T05:23:08+00:00 and should not be modified manually
%% @end

-module(egrpc_grpc_health_v1_health_service).

-export([check/2, check/3]).

-define(GRPC_SERVICE_NAME, 'grpc.health.v1.Health').

%% @doc Call the unary RPC method `Check' of service `grpc.health.v1.Health'.
-spec check(egrpc:channel(), Request) -> Result when
    Request :: egrpc_health_pb:'grpc.health.v1.HealthCheckRequest'(),
    Response :: egrpc_health_pb:'grpc.health.v1.HealthCheckResponse'(),
    Result :: egrpc_stub:unary_ret(Response).
check(Channel, Request) ->
    check(Channel, Request, #{}).

-spec check(egrpc:channel(), Request, Opts) -> Result when
    Result :: egrpc_stub:unary_ret(Response),
    Request :: egrpc_health_pb:'grpc.health.v1.HealthCheckRequest'(),
    Response :: egrpc_health_pb:'grpc.health.v1.HealthCheckResponse'(),
    Opts :: egrpc_stub:opts().
check(Channel, Request, Opts) ->
    RpcDef = egrpc_health_pb:find_rpc_def(?GRPC_SERVICE_NAME, 'Check'),
    Grpc = #{
        rpc_def => RpcDef,
        path => <<"/grpc.health.v1.Health/Check">>,
        pb_module => egrpc_health_pb,
        service_name => ?GRPC_SERVICE_NAME
    },
    egrpc_stub:unary(Channel, Request, Grpc, Opts).
